# Generated by Django 2.0.7 on 2018-07-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
